services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped
    volumes:
      - drive:/drive:rw
      - record:/record:rw

  mysql:
    image: mysql:8.4
    container_name: guac-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: R00tStr0ng!
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: GuacDBStr0ng!
    volumes:
      - dbdata:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d:ro

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    restart: unless-stopped
    depends_on:
      - guacd
      - mysql
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: guacamole_db
      MYSQL_USERNAME: guacamole_user
      MYSQL_PASSWORD: GuacDBStr0ng!
      TOTP_ENABLED: "true"
      RECORDING_SEARCH_PATH: /record
    ports:
      - "8080:8080"
    volumes:
      - drive:/drive:rw
      - record:/record:rw

  caddy:
    image: caddy:2.11.4
    restart: unless-stopped
    depends_on:
      - guacamole
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy_conf:/etc/caddy
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config


volumes:
  dbdata:
  drive:
  record:
  caddy_data:
  caddy_config:
