#cloud-config
packages:
  - ubuntu-desktop
  - winpr3-utils
  - winpr-utils
  - gnome-remote-desktop
package_update: true
package_upgrade: true
runcmd: # cmd's will be run as root
  # Gnome-Remote-Desktop
  # sudo -u gnome-remote-desktop

  - mkdir -p /etc/gnome-remote-desktop/MyCerts
  - openssl req -new -newkey rsa:4096 -days 720 -nodes -x509 -subj /C=NL/ST=Zuid-holland/L=Delft/O=hhs/CN=hhs.nl -out /etc/gnome-remote-desktop/MyCerts/tls.crt -keyout /etc/gnome-remote-desktop/MyCerts/tls.key
  - grdctl --headless rdp set-tls-key /etc/gnome-remote-desktop/MyCerts/tls.key
  - grdctl --headless rdp set-tls-cert /etc/gnome-remote-desktop/tls.crt
  - grdctl --headless rdp enable
  - systemctl enable gnome-remote-desktop-headless.service
  - systemctl enable gnome-remote-desktop.service

  - reboot
